name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-west-3 | \
          docker login --username AWS \
          --password-stdin 922842442607.dkr.ecr.eu-west-3.amazonaws.com

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build & Push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t 922842442607.dkr.ecr.eu-west-3.amazonaws.com/employees-api:${IMAGE_TAG} \
            --push \
            .

      - name: Deploy CDK
        run: |
          cd infra
          npm install
          npx cdk deploy \
            --require-approval never \
            -c imageTag=${IMAGE_TAG}
